/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TravelGuideRouteImport } from './routes/travel-guide'
import { Route as ReelsRouteImport } from './routes/reels'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as MemoriesRouteImport } from './routes/memories'
import { Route as MapRouteImport } from './routes/map'
import { Route as HelpRouteImport } from './routes/help'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SiteSiteIdRouteImport } from './routes/site.$siteId'
import { Route as PlacePlaceIdRouteImport } from './routes/place.$placeId'

const TravelGuideRoute = TravelGuideRouteImport.update({
  id: '/travel-guide',
  path: '/travel-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const ReelsRoute = ReelsRouteImport.update({
  id: '/reels',
  path: '/reels',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoriesRoute = MemoriesRouteImport.update({
  id: '/memories',
  path: '/memories',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteSiteIdRoute = SiteSiteIdRouteImport.update({
  id: '/site/$siteId',
  path: '/site/$siteId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacePlaceIdRoute = PlacePlaceIdRouteImport.update({
  id: '/place/$placeId',
  path: '/place/$placeId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/explore': typeof ExploreRoute
  '/guide': typeof GuideRoute
  '/help': typeof HelpRoute
  '/map': typeof MapRoute
  '/memories': typeof MemoriesRoute
  '/quiz': typeof QuizRoute
  '/reels': typeof ReelsRoute
  '/travel-guide': typeof TravelGuideRoute
  '/place/$placeId': typeof PlacePlaceIdRoute
  '/site/$siteId': typeof SiteSiteIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/explore': typeof ExploreRoute
  '/guide': typeof GuideRoute
  '/help': typeof HelpRoute
  '/map': typeof MapRoute
  '/memories': typeof MemoriesRoute
  '/quiz': typeof QuizRoute
  '/reels': typeof ReelsRoute
  '/travel-guide': typeof TravelGuideRoute
  '/place/$placeId': typeof PlacePlaceIdRoute
  '/site/$siteId': typeof SiteSiteIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/explore': typeof ExploreRoute
  '/guide': typeof GuideRoute
  '/help': typeof HelpRoute
  '/map': typeof MapRoute
  '/memories': typeof MemoriesRoute
  '/quiz': typeof QuizRoute
  '/reels': typeof ReelsRoute
  '/travel-guide': typeof TravelGuideRoute
  '/place/$placeId': typeof PlacePlaceIdRoute
  '/site/$siteId': typeof SiteSiteIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/explore'
    | '/guide'
    | '/help'
    | '/map'
    | '/memories'
    | '/quiz'
    | '/reels'
    | '/travel-guide'
    | '/place/$placeId'
    | '/site/$siteId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/explore'
    | '/guide'
    | '/help'
    | '/map'
    | '/memories'
    | '/quiz'
    | '/reels'
    | '/travel-guide'
    | '/place/$placeId'
    | '/site/$siteId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/explore'
    | '/guide'
    | '/help'
    | '/map'
    | '/memories'
    | '/quiz'
    | '/reels'
    | '/travel-guide'
    | '/place/$placeId'
    | '/site/$siteId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  ExploreRoute: typeof ExploreRoute
  GuideRoute: typeof GuideRoute
  HelpRoute: typeof HelpRoute
  MapRoute: typeof MapRoute
  MemoriesRoute: typeof MemoriesRoute
  QuizRoute: typeof QuizRoute
  ReelsRoute: typeof ReelsRoute
  TravelGuideRoute: typeof TravelGuideRoute
  PlacePlaceIdRoute: typeof PlacePlaceIdRoute
  SiteSiteIdRoute: typeof SiteSiteIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/travel-guide': {
      id: '/travel-guide'
      path: '/travel-guide'
      fullPath: '/travel-guide'
      preLoaderRoute: typeof TravelGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reels': {
      id: '/reels'
      path: '/reels'
      fullPath: '/reels'
      preLoaderRoute: typeof ReelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memories': {
      id: '/memories'
      path: '/memories'
      fullPath: '/memories'
      preLoaderRoute: typeof MemoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site/$siteId': {
      id: '/site/$siteId'
      path: '/site/$siteId'
      fullPath: '/site/$siteId'
      preLoaderRoute: typeof SiteSiteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/place/$placeId': {
      id: '/place/$placeId'
      path: '/place/$placeId'
      fullPath: '/place/$placeId'
      preLoaderRoute: typeof PlacePlaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  ExploreRoute: ExploreRoute,
  GuideRoute: GuideRoute,
  HelpRoute: HelpRoute,
  MapRoute: MapRoute,
  MemoriesRoute: MemoriesRoute,
  QuizRoute: QuizRoute,
  ReelsRoute: ReelsRoute,
  TravelGuideRoute: TravelGuideRoute,
  PlacePlaceIdRoute: PlacePlaceIdRoute,
  SiteSiteIdRoute: SiteSiteIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
